version: '3.9'

services:
  db-test:
    container_name: spc-db-test
    image: postgres:16.2
    environment:
      POSTGRES_DB: spc-db-test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "8001:5432" # default postgres port