version: '3.9'

services:
  app:
    container_name: spc-backend-app
    # build by using Dockerfile in root directory (.)
    build:
      context: .
      dockerfile: Dockerfile
      args: # arguments that are passed to the dockerfile
        DB_URL: ${DB_URL}
        PG_USER: ${PG_USER}
        PG_PASSWORD: ${PG_PASSWORD}
    ports:
      - "8080:8080" # Map to port exposed to host machine (8080)
    environment:
        DB_URL: jdbc:postgresql://db:5432/postgres
        PG_USER: postgres
        PG_PASSWORD: postgres
    depends_on:
      - db
  db:
    container_name: spc-db
    image: postgres:16.2
    environment:
      POSTGRES_DB: spc-db
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    ports:
      - "5432:5432" # default postgres port
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist postgres data through restarts


volumes:
  postgres_data: # Define volume for postgres data persistence